#!/bin/sh

desc="assign expression level (10%ile interval) groups from genes_fpkm.tracking (cufflinks/cuffdiff)"
usage="usage: `basename $0` [-o outputdir] [-c column-name-of-gene] genes_fpkm.tracking"

colname="gene_id"
outdir="./assignedPer10"

while getopts ho:c: opt
do
	case ${opt} in
		h)
      		echo ${desc}
      		echo ${usage}
      		exit 1;;
    c)
      colname=${OPTARG};;
    o)
      outdir=${OPTARG};;
		\?)
      echo ${usage}
			exit 1;;
	esac
done

shift `expr $OPTIND - 1`

mkdir -p $outdir

Rscript - $* <<EOS

read.genes_fpkm <- function(file, genename='gene_id')
{
  X <- read.table(file,head=TRUE)
  g <- strsplit(as.character(X[[genename]]),',')
  fpkm <- as.matrix(X[,grep('_?FPKM$',colnames(X))])
  fpkm <- fpkm[rep.int(seq_along(g),sapply(g,length)),,drop=FALSE]
  colnames(fpkm) <- sub('_?FPKM$','',colnames(fpkm))
  g <- unlist(g)
  apply(fpkm,2,function(x) tapply(x,unlist(g),mean))
}

assignExprGroupPer10<- function(fpkm)
{
  glabel <- paste0('q',seq(0,90,10),'to',seq(10,100,10),'th')
  egroup <- apply(fpkm,2,function(x)
	  cut(x,breaks=quantile(x[x>0],seq(0,1,0.1)),include.lowest=TRUE,label=glabel)
  )          
  egroup[is.na(egroup)] <- 'zero'
  rownames(egroup) <- rownames(fpkm)
  data.frame(lapply(data.frame(egroup),function(x){
    factor(x,c('zero',glabel),ordered=TRUE)
  }))
}

args <- commandArgs(TRUE)

fpkm <- read.genes_fpkm(args[1],"$colname")
tbl <- assignExprGroupPer10(fpkm)
g <- rownames(tbl)

invisible(mapply(function(x,xname){
	ord <- order(x)
	filename <- paste0("${outdir}/",xname,"_ePer10.txt")
	res <- data.frame(g[ord],x[ord])
	write.table(res,file=filename,quote=FALSE,row.names=FALSE,col.names=FALSE,sep="\t")
}, tbl, colnames(tbl)))
EOS

